In [14]:
%reload_ext autoreload
%autoreload 2

In [15]:
# from kret_studies import *
# from kret_studies.notebook import *
# from kret_studies.complex import *

# logger = get_notebook_logger()

In [16]:
from waymo_agent.notebook_imports import *

In [17]:
from waymo_agent import *
from waymo_agent.osmnx import *
from waymo_agent.data_classes import *
from waymo_agent.action_heuristic import *
from waymo_agent.graph_env import *
from waymo_agent.simulation import *
from kret_sandbox.VIS import dtt

In [18]:
config = EnvConfig()
plt_cfg = PlotConfig()

In [19]:
env = RideShareEnv(config, plt_cfg)
G = env.G
cfg = env.config

Assigned lambda values to nodes. Total lambda: 1.5181 (target: 1.5640)

/Users/Akseldkw/micromamba/envs/kret_312/lib/python3.12/site-packages/gymnasium/spaces/box.py:236: UserWarning: WARN: Box low's precision lowered by casting to float32, current low.dtype=float64
  gym.logger.warn(
/Users/Akseldkw/micromamba/envs/kret_312/lib/python3.12/site-packages/gymnasium/spaces/box.py:306: UserWarning: WARN: Box high's precision lowered by casting to float32, current high.dtype=float64
  gym.logger.warn(

In [33]:
s, info = env.reset()

In [34]:
def get_obvs_tuple(env: RideShareEnv):
    veh = env.observation_curr["vehicles"]
    req = env.observation_curr["pending_requests"]
    rides = env.observation_curr["active_rides"]
    return veh, req, rides

In [35]:
veh, req, rides = get_obvs_tuple(env)
veh.shape, req.shape, rides.shape

((16, 6), (25, 21), (16, 18))

In [36]:
action_rnd = env.action_space.sample()
dispatches = pd.DataFrame({"dispatch": action_rnd["dispatch"]})
prices = pd.DataFrame({"prices": action_rnd["prices"]})
reposition = pd.DataFrame(action_rnd["reposition"], columns=["x", "y"])
# action_rnd["dispatch"] = np.full(action_rnd["dispatch"].shape, cfg.no_action_id, dtype=np.int32)
# action_rnd["reposition"] = np.array([[-0.1, -0.1], [0.1, 0.1]], dtype=np.float32)
env.action_space.contains(action_rnd)

True

## Pre-Step

In [37]:
# env.config.max_new_requests_per_step = 0

In [38]:
# action_rnd["dispatch"][2] = 0
# action_rnd["dispatch"][3] = 1
# action["dispatch"] = np.full(action["dispatch"].shape, cfg.no_action_id, dtype=np.int32)
env._validate_action(action_rnd)
action_rnd["dispatch"]

array([ 2,  4, 12,  5, 13,  3,  9,  5,  8,  7, 11,  8,  6,  8, 14,  8,  3,
       11, 12, -1, 15,  4, 13, 12,  9])

In [41]:
dtt([req[req.f_valid], veh, rides], n=12, how="head", titles=["Requests", "Vehicles", "Rides"])

In [42]:
dtt([env.breadcrumbs, env.DiscardedRequests])

ValueError: No objects to concatenate

# Take Step

In [ ]:
obs, reward, trunc, term, info = env.step(action_rnd)

16