In [1]:
%reload_ext autoreload
%autoreload 2

In [2]:
from waymo_agent import *

In [3]:
# from kret_studies import *
# from kret_studies.notebook import *
# from kret_studies.complex import *

# logger = get_notebook_logger()

In [4]:
from waymo_agent import *
from waymo_agent.osmnx import *
from waymo_agent.data_classes import *
from waymo_agent.action_heuristic import *
from waymo_agent.graph_env import *
from waymo_agent.simulation import *
from kret_sandbox.VIS import dtt

#### Load ENV

In [5]:
def get_obvs_tuple(env: RideShareEnv):
    veh = env.observation_curr["vehicles"]
    req = env.observation_curr["pending_requests"]
    rides = env.observation_curr["active_rides"]
    return veh, req, rides

In [6]:
envconfig = EnvConfig()
cfg = envconfig

In [7]:
env = RideShareEnv(cfg)
G = env.graph

Assigned lambda values to nodes. Total lambda: 2.1829 (target: 2.3460)

/Users/Akseldkw/micromamba/envs/kret_312/lib/python3.12/site-packages/gymnasium/spaces/box.py:236: UserWarning: WARN: Box low's precision lowered by casting to float32, current low.dtype=float64
  gym.logger.warn(
/Users/Akseldkw/micromamba/envs/kret_312/lib/python3.12/site-packages/gymnasium/spaces/box.py:306: UserWarning: WARN: Box high's precision lowered by casting to float32, current high.dtype=float64
  gym.logger.warn(

In [8]:
s, info = env.reset()

In [9]:
action = env.action_space.sample()

In [10]:
# obs, reward, terminated, truncated, info = env.step(action)

In [11]:
veh, req, rides = get_obvs_tuple(env)

In [12]:
from waymo_agent.data_classes.supply_demand_df import SupplyDemandDF


get_sd_ratio(cfg, req, veh)[0]

np.float64(0.9999822711311133)

In [13]:
dtt([veh, rides], cols_per_row=1)

In [14]:
fig, ax = env.render()

In [15]:
# fig